// Code generated by protoc-gen-go. DO NOT EDIT.
// source: client.proto

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	client.proto
	main.proto
	server.proto

It has these top-level messages:
	C2SLogin
	C2SChat
	Package
	S2CResult
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type C2SCmd int32

const (
	C2SCmd_None  C2SCmd = 0
	C2SCmd_Login C2SCmd = 1
	C2SCmd_Chat  C2SCmd = 2
)

var C2SCmd_name = map[int32]string{
	0: "None",
	1: "Login",
	2: "Chat",
}
var C2SCmd_value = map[string]int32{
	"None":  0,
	"Login": 1,
	"Chat":  2,
}

func (x C2SCmd) String() string {
	return proto.EnumName(C2SCmd_name, int32(x))
}
func (C2SCmd) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type C2SLogin struct {
	User   string `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Passwd string `protobuf:"bytes,2,opt,name=passwd" json:"passwd,omitempty"`
}

func (m *C2SLogin) Reset()                    { *m = C2SLogin{} }
func (m *C2SLogin) String() string            { return proto.CompactTextString(m) }
func (*C2SLogin) ProtoMessage()               {}
func (*C2SLogin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *C2SLogin) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *C2SLogin) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

type C2SChat struct {
	Count   uint32 `protobuf:"varint,1,opt,name=count" json:"count,omitempty"`
	Context string `protobuf:"bytes,2,opt,name=context" json:"context,omitempty"`
}

func (m *C2SChat) Reset()                    { *m = C2SChat{} }
func (m *C2SChat) String() string            { return proto.CompactTextString(m) }
func (*C2SChat) ProtoMessage()               {}
func (*C2SChat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *C2SChat) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *C2SChat) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

func init() {
	proto.RegisterType((*C2SLogin)(nil), "protocol.C2SLogin")
	proto.RegisterType((*C2SChat)(nil), "protocol.C2SChat")
	proto.RegisterEnum("protocol.C2SCmd", C2SCmd_name, C2SCmd_value)
}

func init() { proto.RegisterFile("client.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 167 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0xc9, 0x4c,
	0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0xc9, 0xf9, 0x39, 0x4a,
	0x66, 0x5c, 0x1c, 0xce, 0x46, 0xc1, 0x3e, 0xf9, 0xe9, 0x99, 0x79, 0x42, 0x42, 0x5c, 0x2c, 0xa5,
	0xc5, 0xa9, 0x45, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x90, 0x18, 0x17, 0x5b,
	0x41, 0x62, 0x71, 0x71, 0x79, 0x8a, 0x04, 0x13, 0x58, 0x14, 0xca, 0x53, 0xb2, 0xe4, 0x62, 0x77,
	0x36, 0x0a, 0x76, 0xce, 0x48, 0x2c, 0x11, 0x12, 0xe1, 0x62, 0x4d, 0xce, 0x2f, 0xcd, 0x2b, 0x01,
	0xeb, 0xe3, 0x0d, 0x82, 0x70, 0x84, 0x24, 0xb8, 0xd8, 0x93, 0xf3, 0xf3, 0x4a, 0x52, 0x2b, 0x4a,
	0xa0, 0x3a, 0x61, 0x5c, 0x2d, 0x75, 0x2e, 0x36, 0x90, 0xd6, 0xdc, 0x14, 0x21, 0x0e, 0x2e, 0x16,
	0xbf, 0xfc, 0xbc, 0x54, 0x01, 0x06, 0x21, 0x4e, 0x2e, 0x56, 0xb0, 0x1b, 0x04, 0x18, 0x41, 0x82,
	0x20, 0x63, 0x05, 0x98, 0x92, 0xd8, 0xc0, 0xae, 0x34, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xe0,
	0xfe, 0x83, 0x4b, 0xbc, 0x00, 0x00, 0x00,
}
