// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol.proto

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	protocol.proto

It has these top-level messages:
	Package
	C2SChat
	S2CResult
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 客户端发给服务器的协议定义
type C2SCmd int32

const (
	C2SCmd_Abnormal C2SCmd = 0
	C2SCmd_Chat     C2SCmd = 1
)

var C2SCmd_name = map[int32]string{
	0: "Abnormal",
	1: "Chat",
}
var C2SCmd_value = map[string]int32{
	"Abnormal": 0,
	"Chat":     1,
}

func (x C2SCmd) String() string {
	return proto.EnumName(C2SCmd_name, int32(x))
}
func (C2SCmd) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// 服务器发给客户端的协议定义
type S2CCmd int32

const (
	S2CCmd_Invalid S2CCmd = 0
	S2CCmd_Result  S2CCmd = 1
)

var S2CCmd_name = map[int32]string{
	0: "Invalid",
	1: "Result",
}
var S2CCmd_value = map[string]int32{
	"Invalid": 0,
	"Result":  1,
}

func (x S2CCmd) String() string {
	return proto.EnumName(S2CCmd_name, int32(x))
}
func (S2CCmd) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// Package 数据包定义
type Package struct {
	Serial int32  `protobuf:"varint,1,opt,name=serial" json:"serial,omitempty"`
	Buff   []byte `protobuf:"bytes,2,opt,name=buff,proto3" json:"buff,omitempty"`
}

func (m *Package) Reset()                    { *m = Package{} }
func (m *Package) String() string            { return proto.CompactTextString(m) }
func (*Package) ProtoMessage()               {}
func (*Package) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Package) GetSerial() int32 {
	if m != nil {
		return m.Serial
	}
	return 0
}

func (m *Package) GetBuff() []byte {
	if m != nil {
		return m.Buff
	}
	return nil
}

type C2SChat struct {
	Index   uint64 `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	Context string `protobuf:"bytes,2,opt,name=context" json:"context,omitempty"`
}

func (m *C2SChat) Reset()                    { *m = C2SChat{} }
func (m *C2SChat) String() string            { return proto.CompactTextString(m) }
func (*C2SChat) ProtoMessage()               {}
func (*C2SChat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *C2SChat) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *C2SChat) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

type S2CResult struct {
	Context string `protobuf:"bytes,1,opt,name=context" json:"context,omitempty"`
}

func (m *S2CResult) Reset()                    { *m = S2CResult{} }
func (m *S2CResult) String() string            { return proto.CompactTextString(m) }
func (*S2CResult) ProtoMessage()               {}
func (*S2CResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *S2CResult) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

func init() {
	proto.RegisterType((*Package)(nil), "protocol.Package")
	proto.RegisterType((*C2SChat)(nil), "protocol.C2SChat")
	proto.RegisterType((*S2CResult)(nil), "protocol.S2CResult")
	proto.RegisterEnum("protocol.C2SCmd", C2SCmd_name, C2SCmd_value)
	proto.RegisterEnum("protocol.S2CCmd", S2CCmd_name, S2CCmd_value)
}

func init() { proto.RegisterFile("protocol.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 210 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0x41, 0x4b, 0x85, 0x40,
	0x14, 0x85, 0xdf, 0x84, 0x6f, 0xc6, 0x77, 0x7b, 0xc4, 0x70, 0x89, 0x70, 0x69, 0x42, 0x20, 0x2e,
	0x5a, 0x18, 0x2d, 0x5a, 0xc6, 0xac, 0xda, 0xc5, 0xf8, 0x0b, 0x46, 0x1d, 0x4b, 0x1a, 0x67, 0x42,
	0xc7, 0xf0, 0xe7, 0x87, 0x63, 0x42, 0x6f, 0x77, 0x3e, 0xf8, 0xce, 0x3d, 0x5c, 0xb8, 0xf9, 0x1e,
	0x9d, 0x77, 0x8d, 0x33, 0x8f, 0x21, 0x60, 0xbc, 0x73, 0xf6, 0x0c, 0xec, 0x5d, 0x35, 0x5f, 0xea,
	0x43, 0xe3, 0x1d, 0xd0, 0x49, 0x8f, 0xbd, 0x32, 0x09, 0x49, 0x49, 0x7e, 0x94, 0x7f, 0x84, 0x08,
	0x51, 0x3d, 0x77, 0x5d, 0x72, 0x95, 0x92, 0xfc, 0x2c, 0x43, 0xce, 0x5e, 0x80, 0x89, 0xb2, 0x12,
	0x9f, 0xca, 0xe3, 0x2d, 0x1c, 0x7b, 0xdb, 0xea, 0x25, 0xb4, 0x22, 0xb9, 0x01, 0x26, 0xc0, 0x1a,
	0x67, 0xbd, 0x5e, 0x7c, 0xe8, 0x9d, 0xe4, 0x8e, 0xd9, 0x03, 0x9c, 0xaa, 0x52, 0x48, 0x3d, 0xcd,
	0xc6, 0xff, 0xd7, 0xc8, 0x85, 0x56, 0xa4, 0x40, 0xd7, 0x85, 0xa1, 0xc5, 0x33, 0xc4, 0xaf, 0xb5,
	0x75, 0xe3, 0xa0, 0x0c, 0x3f, 0x60, 0x0c, 0xd1, 0x3a, 0xcb, 0x49, 0x71, 0x0f, 0xb4, 0x2a, 0xc5,
	0x6a, 0x5c, 0x03, 0x7b, 0xb3, 0x3f, 0xca, 0xf4, 0x2d, 0x3f, 0x20, 0x00, 0xdd, 0x8e, 0x73, 0x52,
	0xd3, 0xf0, 0xe7, 0xd3, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x11, 0x67, 0x34, 0xe5, 0x00, 0x01,
	0x00, 0x00,
}
