// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server.proto

package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type S2CCmd int32

const (
	S2CCmd_Result S2CCmd = 0
)

var S2CCmd_name = map[int32]string{
	0: "Result",
}
var S2CCmd_value = map[string]int32{
	"Result": 0,
}

func (x S2CCmd) String() string {
	return proto.EnumName(S2CCmd_name, int32(x))
}
func (S2CCmd) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

type S2CResult struct {
	Context string `protobuf:"bytes,1,opt,name=context" json:"context,omitempty"`
}

func (m *S2CResult) Reset()                    { *m = S2CResult{} }
func (m *S2CResult) String() string            { return proto.CompactTextString(m) }
func (*S2CResult) ProtoMessage()               {}
func (*S2CResult) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *S2CResult) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

func init() {
	proto.RegisterType((*S2CResult)(nil), "protocol.S2CResult")
	proto.RegisterEnum("protocol.S2CCmd", S2CCmd_name, S2CCmd_value)
}

func init() { proto.RegisterFile("server.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 101 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x4e, 0x2d, 0x2a,
	0x4b, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0xc9, 0xf9, 0x39, 0x4a,
	0xaa, 0x5c, 0x9c, 0xc1, 0x46, 0xce, 0x41, 0xa9, 0xc5, 0xa5, 0x39, 0x25, 0x42, 0x12, 0x5c, 0xec,
	0xc9, 0xf9, 0x79, 0x25, 0xa9, 0x15, 0x25, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x30, 0xae,
	0x96, 0x08, 0x17, 0x5b, 0xb0, 0x91, 0xb3, 0x73, 0x6e, 0x8a, 0x10, 0x17, 0x17, 0x1b, 0x44, 0xb5,
	0x00, 0x43, 0x12, 0x1b, 0xd8, 0x18, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7c, 0x26, 0x5e,
	0x47, 0x5d, 0x00, 0x00, 0x00,
}
